# Generated by Django 3.2.5 on 2021-07-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='dog-2890078_1280.jpeg', upload_to='profile_pics'),
        ),
    ]
