# Generated by Django 3.2.5 on 2021-07-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210708_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='shutterstock_690109897.jpeg', upload_to='profile_pics'),
        ),
    ]
