# Generated by Django 3.2.5 on 2021-07-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='download (3).jpeg', upload_to='profile_pics'),
        ),
    ]
