# Generated by Django 3.2.5 on 2021-07-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='CPSC 103', max_length=10, verbose_name='What is the course code?'),
        ),
    ]
