# Generated by Django 3.2.5 on 2021-07-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_coop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coop',
            name='image',
        ),
    ]
